<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Version>1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.11" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
    <PackageReference Include="FluentAvaloniaUI" Version="2.5.0" />
    <PackageReference Include="FluentIcons.Avalonia.Fluent" Version="2.0.317" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
  </ItemGroup>
</Project>
